### ISSUE TITLE
ModuleNotFoundError: No module named 'pymatting_aot.aot' 你好，怎解决这个问题啊，也是版本对的啊

### ISSUE THREAD

**Issue by tsruixi** [itainf/aiphoto#3]
Traceback (most recent call last):
  File "D:\install_dir\Anaconda\Ana\envs\AIPhoto\lib\site-packages\pymatting_aot\cc.py", line 36, in <module>
    import pymatting_aot.aot
ModuleNotFoundError: No module named 'pymatting_aot.aot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/BS/aiphoto-master/m_web/web.py", line 3, in <module>
    import m_web.upload as upload
  File "D:\BS\aiphoto-master\m_web\upload.py", line 5, in <module>
    from to_background import to_background
  File "D:\BS\aiphoto-master\to_background\to_background.py", line 1, in <module>
    from pymatting import *
  File "D:\install_dir\Anaconda\Ana\envs\AIPhoto\lib\site-packages\pymatting\__init__.py", line 2, in <module>
    import pymatting_aot.cc
  File "D:\install_dir\Anaconda\Ana\envs\AIPhoto\lib\site-packages\pymatting_aot\cc.py", line 54, in <module>
    compile_modules()
  File "D:\install_dir\Anaconda\Ana\envs\AIPhoto\lib\site-packages\pymatting_aot\cc.py", line 8, in compile_modules
    cc = CC("aot")
  File "D:\install_dir\Anaconda\Ana\envs\AIPhoto\lib\site-packages\numba\pycc\cc.py", line 65, in __init__
    self._toolchain = Toolchain()
  File "D:\install_dir\Anaconda\Ana\envs\AIPhoto\lib\site-packages\numba\pycc\platform.py", line 78, in __init__
    self._raise_external_compiler_error()
  File "D:\install_dir\Anaconda\Ana\envs\AIPhoto\lib\site-packages\numba\pycc\platform.py", line 121, in _raise_external_compiler_error
    raise RuntimeError(msg)
RuntimeError: Attempted to compile AOT function without the compiler used by `numpy.distutils` present

**Comment by tsruixi** [comment]
已经解决了，安装VS编译器即可解决该问题
